### sklearn.preprocessing.PolynomialFeatures
** _class_ sklearn.preprocessing.PolynomialFeatures(_degree=2_, _*_, _interaction_only=False_, _include_bias=True_, _order='C'_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/7db5b6a98/sklearn/preprocessing/_polynomial.py#L30)[¶](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html#sklearn.preprocessing.PolynomialFeatures "Permalink to this definition")

* Generate polynomial and interaction features.

Generate a new feature matrix consisting of all polynomial combinations of the features with degree less than or equal to the specified degree. For example, if an input sample is two dimensional and of the form [a, b], the degree-2 polynomial features are [1, a, b, a^2, ab, b^2].

Read more in the  [User Guide](https://scikit-learn.org/stable/modules/preprocessing.html#polynomial-features).

In [4]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# 다항식으로 변환한 단항식 생성, [[0,1],[2,3]]의 2X2 행렬 생성
X = np.arange(4).reshape(2,2)
print('일차 단항식 계수 feature:\n',X )

# degree = 2 인 2차 다항식으로 변환하기 위해 PolynomialFeatures를 이용하여 변환
poly = PolynomialFeatures(degree=2)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature:\n', poly_ftr) 

poly = PolynomialFeatures(degree=3)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 3차 다항식 계수 feature:\n', poly_ftr)

일차 단항식 계수 feature:
 [[0 1]
 [2 3]]
변환된 2차 다항식 계수 feature:
 [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]
변환된 3차 다항식 계수 feature:
 [[ 1.  0.  1.  0.  0.  1.  0.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.  8. 12. 18. 27.]]


### sklearn.pipeline.Pipeline
** _class_ sklearn.pipeline.Pipeline(_steps_, _*_, _memory=None_, _verbose=False_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/7db5b6a98/sklearn/pipeline.py#L52)[¶](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline "Permalink to this definition")

* Pipeline of transforms with a final estimator.

Sequentially apply a list of transforms and a final estimator. Intermediate steps of the pipeline must be ‘transforms’, that is, they must implement  `fit`  and  `transform`  methods. The final estimator only needs to implement  `fit`. The transformers in the pipeline can be cached using  `memory`  argument.

The purpose of the pipeline is to assemble several steps that can be cross-validated together while setting different parameters. For this, it enables setting parameters of the various steps using their names and the parameter name separated by a  `'__'`, as in the example below. A step’s estimator may be replaced entirely by setting the parameter with its name to another estimator, or a transformer removed by setting it to  `'passthrough'`  or  `None`.

Read more in the  [User Guide](https://scikit-learn.org/stable/modules/compose.html#pipeline).

In [7]:
# 파이프라인 이용 다항 회귀
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

def polynomial_func(X):
    y = 1 + 2*X + X**2 + X**3 
    return y

# Pipeline 객체로 Streamline 하게 Polynomial Feature변환과 Linear Regression을 연결
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression())])

X = np.arange(4).reshape(2,2)
y = polynomial_func(X)

model = model.fit(X, y)
print('Polynomial 회귀 계수\n', np.round(model.named_steps['linear'].coef_, 2))

Polynomial 회귀 계수
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]


In [10]:
model.named_steps

{'poly': PolynomialFeatures(degree=3), 'linear': LinearRegression()}

In [14]:
model.n_features_in_

2

In [16]:
model

Pipeline(steps=[('poly', PolynomialFeatures(degree=3)),
                ('linear', LinearRegression())])