In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

titanic_df = pd.read_csv('c:/Users/seopa/Downloads/titanic_train.csv')
titanic_df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [2]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [3]:
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
titanic_df['Cabin'].fillna('N', inplace=True)
titanic_df['Embarked'].fillna('S', inplace=True)
titanic_df['Fare'].fillna('N', inplace=True)

In [5]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
titanic_df_test = pd.read_csv('c:/Users/seopa/Downloads/titanic_test.csv')

In [7]:
titanic_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [8]:
titanic_df_test['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
titanic_df_test['Cabin'].fillna('N', inplace=True)
titanic_df_test['Fare'].fillna('N', inplace=True)

In [9]:
titanic_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         418 non-null    object 
 9   Cabin        418 non-null    object 
 10  Embarked     418 non-null    object 
dtypes: float64(1), int64(4), object(6)
memory usage: 36.0+ KB


In [10]:
print(f'성별의 값 분포: {titanic_df["Sex"].value_counts()}')

성별의 값 분포: male      577
female    314
Name: Sex, dtype: int64


In [11]:
print(f'Cabin의 값 분포: {titanic_df["Cabin"].value_counts()}')

Cabin의 값 분포: N              687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ... 
E34              1
C7               1
C54              1
E36              1
C148             1
Name: Cabin, Length: 148, dtype: int64


In [12]:
print(f'Embarked의 값 분포: {titanic_df["Embarked"].value_counts()}')

Embarked의 값 분포: S    646
C    168
Q     77
Name: Embarked, dtype: int64


In [13]:
from sklearn.preprocessing import LabelEncoder

def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    return df

def drop_features(df):
    df.drop(['PassengerId','Name','SibSp','Ticket','Parch','Fare'], axis=1, inplace=True)
    return df

def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        df[feature] = le.fit_transform(df[feature])
    return df

def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

In [14]:
import pandas as pd
titanic_df = pd.read_csv('c:/Users/seopa/Downloads/titanic_train.csv')
titanic_df_test = pd.read_csv('c:/Users/seopa/Downloads/titanic_test.csv')

In [15]:
titanic_df = transform_features(titanic_df)
titanic_df_test = transform_features(titanic_df_test)
    

### Features 와 label 분리

In [17]:
label = titanic_df['Survived']
features = titanic_df.drop(columns='Survived')

In [19]:
label

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [18]:
features

Pclass  Sex        Age  Cabin  Embarked
0         3    1  22.000000      7         3
1         1    0  38.000000      2         0
2         3    0  26.000000      7         3
3         1    0  35.000000      2         3
4         3    1  35.000000      7         3
..      ...  ...        ...    ...       ...
886       2    1  27.000000      7         3
887       1    0  19.000000      1         3
888       3    0  29.699118      7         3
889       1    1  26.000000      2         0
890       3    1  32.000000      7         2

[891 rows x 5 columns]

#### datascaling

In [20]:
# StandardScaler 를 이용한 Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
titanic_train_scaled = scaler.fit_transform(features)

In [21]:
titanic_train_scaled

array([[ 0.82737724,  0.73769513, -0.5924806 ,  0.51129323,  0.56273365],
       [-1.56610693, -1.35557354,  0.63878901, -1.91449093, -2.00852627],
       [ 0.82737724, -1.35557354, -0.2846632 ,  0.51129323,  0.56273365],
       ...,
       [ 0.82737724, -1.35557354,  0.        ,  0.51129323,  0.56273365],
       [-1.56610693,  0.73769513, -0.2846632 , -1.91449093, -2.00852627],
       [ 0.82737724,  0.73769513,  0.17706291,  0.51129323, -0.29435299]])

In [22]:
df_scaled = pd.DataFrame(titanic_train_scaled, columns=['Pclass','Sex','Age','Cabin','Embarked'])

In [23]:
df_scaled.describe()

Pclass           Sex           Age         Cabin      Embarked
count  8.910000e+02  8.910000e+02  8.910000e+02  8.910000e+02  8.910000e+02
mean  -8.772133e-17 -1.156327e-16  2.232906e-16 -6.778466e-17  7.974666e-18
std    1.000562e+00  1.000562e+00  1.000562e+00  1.000562e+00  1.000562e+00
min   -1.566107e+00 -1.355574e+00 -2.253155e+00 -2.884805e+00 -2.008526e+00
25%   -3.693648e-01 -1.355574e+00 -5.924806e-01  5.112932e-01 -2.943530e-01
50%    8.273772e-01  7.376951e-01  0.000000e+00  5.112932e-01  5.627337e-01
75%    8.273772e-01  7.376951e-01  4.079260e-01  5.112932e-01  5.627337e-01
max    8.273772e-01  7.376951e-01  3.870872e+00  9.964501e-01  5.627337e-01

#### decisionTree 를 활용한 예측

In [24]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=0)
clf.fit(df_scaled, label)

DecisionTreeClassifier(random_state=0)

In [37]:
titanic_test_scaled = scaler.fit_transform(titanic_df_test)

result = clf.predict(titanic_test_scaled)

C:\Users\seopa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [26]:
result

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [34]:
y_test = pd.read_csv('c:/Users/seopa/Downloads/titanic_test_y.csv')

In [35]:
y_test = y_test['Survived']

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, result)

0.8110047846889952

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression()

df_clf.fit(df_scaled, label)
df_pred = df_clf.predict(titanic_test_scaled)
print(accuracy_score(y_test, df_pred))

rf_clf.fit(df_scaled, label)
rf_pred = rf_clf.predict(titanic_test_scaled)
print(accuracy_score(y_test, rf_pred))

lr_clf.fit(df_scaled, label)
lr_pred = lr_clf.predict(titanic_test_scaled)
print(accuracy_score(y_test, lr_pred))


0.8110047846889952
0.8181818181818182
0.9473684210526315


C:\Users\seopa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\seopa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
C:\Users\seopa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
import numpy as np
from sklearn.model_selection import cross_val_score

scores = cross_val_score(df_clf, titanic_train_scaled, label, cv=5)

for iter_count, accuracy in enumerate(scores):
    print(iter_count, accuracy)

print(np.mean(scores))

In [54]:
from sklearn.model_selection import GridSearchCV

parameters = {'max_depth':[2,3,5,10],'min_samples_split':[2,3,5], 'min_samples_leaf':[1,5,8]}

grid_dclf = GridSearchCV(df_clf, param_grid=parameters, scoring='accuracy', cv=5)
grid_dclf.fit(df_scaled, label)

print('최적 하이퍼 파라미터:', grid_dclf.best_params_)
print('최고 정확도:', grid_dclf.best_score_)
best_dclf = grid_dclf.best_estimator_

dpredictions = best_dclf.predict(titanic_test_scaled)
accuracy = accuracy_score(y_test, dpredictions)
print('decisiontreeclassifier:',accuracy)

최적 하이퍼 파라미터: {'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2}
최고 정확도: 0.8170547988199109
decisiontreeclassifier: 0.8875598086124402


C:\Users\seopa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [59]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    
    print('오차행렬')
    print(confusion)
    print('정확도:',round(accuracy,3),'정밀도:', round(precision,3),'재현률:', round(recall,3))


In [60]:
get_clf_eval(y_test, result)

오차행렬
[[227  39]
 [ 40 112]]
정확도: 0.811 정밀도: 0.742 재현률: 0.737
