## tf.keras.preprocessing.text.text_to_word_sequence

* tf.keras.preprocessing.text.text_to_word_sequence(
    input_text,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' '
)



* Args
input_text	Input text (string).
filters	list (or concatenation) of characters to filter out, such as punctuation. Default: '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\\t\\n', includes basic punctuation, tabs, and newlines.
lower	boolean. Whether to convert the input to lowercase.
split	str. Separator for word splitting.
Returns
A list of words (or tokens).


In [4]:
# 토큰화하기 (입력된 텍스트를 공백에 맞춰 잘게 나누기)
from tensorflow.keras.preprocessing.text import text_to_word_sequence

text ='해보지 않으면, 해낼 수 없다'

text_to_word_sequence(text) 

['해보지', '않으면', '해낼', '수', '없다']

In [5]:
# split= 을 지정해서 텍스트를 나누는 기준을 설정할 수 있다
text_to_word_sequence(text, split='  ')

['해보지 않으면', ' 해낼 수 없다']

In [6]:
text_to_word_sequence(text, split=',')

['해보지 않으면', ' 해낼 수 없다']

문장을 토큰화하면 이를 이용해 여러가지를 할 수 있음
- 단어 빈도 확인
- 중요 단어 파악

Bag-of-words 라는 방법이 이런 전처리를 일컫는 말 / 같은 단어끼리 따로 따로 가방에 담아 각 가방에 몇 개의 단어가 있는지 세는 기법

### tf.keras.preprocessing.text.Tokenizer

* tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' ',
    char_level=False,
    oov_token=None,
    analyzer=None,
    **kwargs
)


* Args
num_words	the maximum number of words to keep, based on word frequency. Only the most common num_words-1 words will be kept.
filters	a string where each element is a character that will be filtered from the texts. The default is all punctuation, plus tabs and line breaks, minus the ' character.
lower	boolean. Whether to convert the texts to lowercase.
split	str. Separator for word splitting.
char_level	if True, every character will be treated as a token.
oov_token	if given, it will be added to word_index and used to replace out-of-vocabulary words during text_to_sequence calls
analyzer	function. Custom analyzer to split the text. The default analyzer is text_to_word_sequence


* ## Methods

### `fit_on_sequences`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L329-L343)

```
fit_on_sequences(    sequences)
```

Updates internal vocabulary based on a list of sequences.

Required before using  `sequences_to_matrix`  (if  `fit_on_texts`  was never called).

Args

`sequences`

A list of sequence. A "sequence" is a list of integer word indices.

### `fit_on_texts`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L269-L327)

```
fit_on_texts(    texts)
```

Updates internal vocabulary based on a list of texts.

In the case where texts contains lists, we assume each entry of the lists to be a token.

Required before using  `texts_to_sequences`  or  `texts_to_matrix`.

Args

`texts`

can be a list of strings, a generator of strings (for memory-efficiency), or a list of list of strings.

### `get_config`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L526-L555)

```
get_config()
```

Returns the tokenizer configuration as Python dictionary.

The word count dictionaries used by the tokenizer get serialized into plain JSON, so that the configuration can be read by other projects.

Returns

A Python dictionary with the tokenizer configuration.

### `sequences_to_matrix`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L466-L524)

```
sequences_to_matrix(    sequences, mode='binary')
```

Converts a list of sequences into a Numpy matrix.

Args

`sequences`

list of sequences (a sequence is a list of integer word indices).

`mode`

one of "binary", "count", "tfidf", "freq"

Returns

A Numpy matrix.

Raises

`ValueError`

In case of invalid  `mode`  argument, or if the Tokenizer requires to be fit to sample data.

### `sequences_to_texts`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L407-L419)

```
sequences_to_texts(    sequences)
```

Transforms each sequence into a list of text.

Only top  `num_words-1`  most frequent words will be taken into account. Only words known by the tokenizer will be taken into account.

Args

`sequences`

A list of sequences (list of integers).

Returns

A list of texts (strings)

### `sequences_to_texts_generator`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L421-L451)

```
sequences_to_texts_generator(    sequences)
```

Transforms each sequence in  `sequences`  to a list of texts(strings).

Each sequence has to a list of integers. In other words, sequences should be a list of sequences

Only top  `num_words-1`  most frequent words will be taken into account. Only words known by the tokenizer will be taken into account.

Args

`sequences`

A list of sequences.

Yields

Yields individual texts.

### `texts_to_matrix`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L453-L464)

```
texts_to_matrix(    texts, mode='binary')
```

Convert a list of texts to a Numpy matrix.

Args

`texts`

list of strings.

`mode`

one of "binary", "count", "tfidf", "freq".

Returns

A Numpy matrix.

### `texts_to_sequences`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L345-L357)

```
texts_to_sequences(    texts)
```

Transforms each text in texts to a sequence of integers.

Only top  `num_words-1`  most frequent words will be taken into account. Only words known by the tokenizer will be taken into account.

Args

`texts`

A list of texts (strings).

Returns

A list of sequences.

### `texts_to_sequences_generator`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L359-L405)

```
texts_to_sequences_generator(    texts)
```

Transforms each text in  `texts`  to a sequence of integers.

Each item in texts can also be a list, in which case we assume each item of that list to be a token.

Only top  `num_words-1`  most frequent words will be taken into account. Only words known by the tokenizer will be taken into account.

Args

`texts`

A list of texts (strings).

Yields

Yields individual sequences.

### `to_json`

[View source](https://github.com/keras-team/keras/tree/v2.11.0/keras/preprocessing/text.py#L557-L575)

```
to_json(    **kwargs)
```

Returns a JSON string containing the tokenizer configuration.

To load a tokenizer from a JSON string, use  [`keras.preprocessing.text.tokenizer_from_json(json_string)`](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/tokenizer_from_json).

Args

`**kwargs`

Additional keyword arguments to be passed to  `json.dumps()`.

Returns

A JSON string containing the tokenizer configuration

## padding - pad_sequences()

## Embedding() - text_to_sequence (원핫인코딩) 대신 사용 -> 이후 토큰화 진행

In [9]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

# 주어진 문장을 '단어'로 토큰화 하기
# 케라스의 텍스트 전처리와 관련한 함수 중 test_to_word_sequence 함수를 불러 오기
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화 합니다.
result = text_to_word_sequence(text)
print('\n원문:\n', text)
print('\n토큰화:\n', result)

# 단어 빈도수 세기
# 전처리 하려는 세 개의 문장을 정함
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.',
       ]

# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()      # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용

# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력
print('\n단어 카운트:\n', token.word_counts)
# Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict 클래스를 사용

# 출력되는 순서는 랜덤
print('\n문장 카운트:', token.document_count)
print('\n각 단어가 몇개의 문장에 포함되어 있는가:\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']

단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트: 3

각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'합니다': 1, '텍스트의': 2, '나누어': 1, '단어를': 1, '각': 1, '토큰화': 3, '먼저': 1, '딥러닝에서': 2, '인식됩니다': 1, '해야': 1, '단어로': 1, '할': 1, '결과는': 1, '한': 1, '있습니다': 1, '사용': 1, '수': 1})

각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


In [10]:
# 텍스트 리뷰 10개 샘플을 지정
docs = ['너무 재밌네요', '최고에요', '참 잘 만든 영화에요',
       '추천하고 싶은 영화입니다.', '한번 더 보고싶네요',
       '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print('\n리뷰 텍스트, 토큰화 결과:\n', x)

# 패딩, 서로 다른 길이의 데이터를 4로 맞춤
padded_x = pad_sequences(x, 4)
print('\n패딩 결과:\n', padded_x)

# 딥러닝 모델
print('\n딥러닝 모델 시작:')

# 임베딩에 입력될 단어의 수를 지정
word_size = len(token.word_index) +1

# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
             loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print('\n Accuracy: %.4f' % (model.evaluate(padded_x, classes)[1]))

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]

딥러닝 모델 시작:
Epoch 1/20
1/1 [==============================] - 1s 600ms/step - loss: 0.6939 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6918 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6897 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6876 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6855 - accuracy: 0.5000
Epoch 6/20
1/1 [===